# qt-repo-server/nginx.conf

server {
    listen 8080;
    server_name localhost;

    root /usr/share/nginx/html;

    # Mime types cruciais para o Qt Online Installer não baixar arquivos como texto puro
    include /etc/nginx/mime.types;
    types {
        application/xml xml;
        application/x-7z-compressed 7z;
        text/plain sha1;
        application/zip zip;
    }

    # Se o instalador bater na raiz /, entrega o Updates.xml
    location / {
        index Updates.xml;
        try_files $uri $uri/ =404;
    }
}