# qt-repo-server/nginx.conf

server {
    listen 8080;
    server_name localhost;

    # O Nginx servirá os arquivos da pasta que criaremos na imagem Docker
    root /usr/share/nginx/html;
    
    # Adiciona a regra de reescrita para o arquivo Updates.xml
    # Isso permite que os instaladores mais antigos do Qt 
    # encontrem a atualização sem a necessidade de colocar o nome do arquivo na URL
    location / {
        index Updates.xml;
    }
}