# qt-repo-server/nginx.conf

server {
    listen 8080;
    server_name localhost;

    # Mudamos a raiz diretamente para a pasta server onde seus arquivos reais vivem!
    root /usr/share/nginx/html/server;

    include /etc/nginx/mime.types;
    types {
        application/xml xml;
        application/x-7z-compressed 7z;
        text/plain sha1;
        application/zip zip;
    }

    # Se bater na raiz, busca o Updates.xml direto dentro de /server
    location / {
        index Updates.xml;
        try_files $uri $uri/ =404;
    }
}